[package]
name = "process-memory"
version = "0.2.1"
authors = ["Tommoa <tommoa256@gmail.com>"]
readme = "README.md"
license = "MIT"
description = "A rust library that can read/write/inject into other processes."
repository = "https://github.com/Tommoa/rs-process-memory"

[dependencies]
libc = "0.2.15"
log = "0.4.1"

[target.'cfg(target_os="macos")'.dependencies]
mach = "0.0.5"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winnt", "tlhelp32", "memoryapi", "libloaderapi", "minwindef", "processthreadsapi"] }

